import type { Metadata } from "next";

import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"], preload: true });

export const metadata: Metadata = {
  title: "Inicios M&R",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={` ${montserrat.className}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
